package com.example.papers;


public enum Status {
    ACTIVE, INACTIVE, CREATED, SUBMISSION, ASSIGNMENT, REVIEW, DECISION, FINAL_SUBMISSION, FINAL, SUBMITTED, UNDER_REVIEW, APPROVED, REJECTED, FINAL_SUBMITTED, ACCEPTED
}
